version: "3"
services:
  site:
    image: zkamvar/carpentries-docker-test:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/src/
    command: make -C ../src serve-in-container
    depends_on:
      - needs
  needs:
    image: rocker/verse:latest
    volumes:
      - .:/home/docker
    command: make -C /home/docker lesson-md
